name: my_first_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  cloud_firestore: ^6.0.0
  decimal: ^3.2.4
  file_picker: ^10.3.1
  firebase_app_check: ^0.4.0
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.3
  firebase_storage: ^13.0.0
  flutter:
    sdk: flutter
  flutter_cart: ^0.0.9
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.14.4
  flutter_rating_bar: ^4.0.1
  flutter_stripe: ^11.5.0
  flutter_swipe_action_cell: ^3.1.5
  get: ^4.7.2
  google_sign_in: ^7.2.0
  googleapis_auth: ^2.0.0
  http: ^1.5.0
  image_card: ^0.0.4
  image_picker: ^1.1.2
  intl: ^0.20.2
  liquid_glass_renderer: ^0.1.1-dev.26
  lottie: ^3.3.1
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  assets:
      - lib/User_panel/screens/splash_screens/salada/burgers/
      - lib/User_panel/screens/splash_screens/salada/desserts/
      - lib/User_panel/screens/splash_screens/salada/drinks/
      - lib/User_panel/screens/splash_screens/salada/sides/
      - lib/User_panel/screens/splash_screens/salada/salads/
      - lib/User_panel/screens/splash_screens/images/intro.jpg
      - lib/User_panel/screens/splash_screens/images/
      - lib/User_panel/screens/splash_screens/images/junaid.png
      - lib/User_panel/screens/splash_screens/images/sign.jpg
      - assets/splash.json
      # - lib/screens/splash_screens/images/cam3.png
      # - lib/screens/splash_screens/images/cam4.png
      # - lib/screens/splash_screens/images/cam5.png
      # - lib/screens/splash_screens/images/cam6.png
